notifications:
  email:
    recipients:
    - davenicolette@gmail.com
    on_success: change
    on_failure: change
language: ruby
rvm:
- 2.3.1
branches:
  only: master
install:
- bundle install
script:
- rackup 
- rake integration
- kill `cat playservice.pid`
